[build]
publish = "public"
command = "./stackbit-build.sh"

[build.environment]
 HUGO_VERSION = "0.53"

 [context.production.environment]
  HUGO_VERSION = "0.53"

 [context.deploy-preview.environment]
 HUGO_VERSION = "0.53"